server:
  port: 18080

spring:
  application:
    name: javaAiStudent
  ai:
    deepseek:
      api-key: sk-5b3f957c53574a49b1cec161a4f8293c
      chat:
        model: deepseek-v4-flash
        temperature: 0.7
    # 阿里百炼 DashScope（通义千问）
    dashscope:
      api-key: sk-ws-H.EIMYEXE.MAym.MEYCIQCw_s-3HFqnC9ojNRw3HsiKbhwBwMoEp4QbrnENpFPUwwIhAMGsw5UKHBSVRjgp8birECTaoI15VR9Vg3LlEa4OPIAh
      chat:
        options:
          model: qwen-plus   # 也可换 qwen-turbo / qwen-max / qwq-plus
